version: '3.9'

services:
  playwright:
    build:
      context: .
      dockerfile: docker/CI/playwright/Dockerfile
    restart: "no"
    depends_on:
      pocketbase:
        condition: service_healthy
    container_name: rl-playwright

  vitest:
    build:
      context: .
      dockerfile: docker/CI/vitest/Dockerfile
    stdin_open: true
    tty: true
    restart: "no"
    container_name: rl-vitest

  eslint:
    build:
      context: .
      dockerfile: docker/CI/eslint/Dockerfile
    restart: "no"
    container_name: rl-eslint

  golangci:
    build:
      context: .
      dockerfile: docker/CI/golangci/Dockerfile
    restart: "no"
    container_name: rl-golangci
    healthcheck:
      test: wget --no-verbose --tries=1 --spider http://localhost:8090/api/health || exit 1
      interval: 10s
      timeout: 5s
      retries: 5

  pocketbase:
    build:
      context: .
      dockerfile: docker/build/pocketbase/Dockerfile
    restart: "no"
    container_name: rl-pocketbase
    healthcheck:
      test: wget --no-verbose --tries=1 --spider http://localhost:8090/api/health || exit 1
      interval: 20s
      timeout: 5s
      retries: 5
