version: '3.9'

services:
  caddy:
    image: caddy:2.7.4-alpine
    restart: unless-stopped
    container_name: rl-caddy
    ports:
      - 80:80
      - 443:443
      - 443:443/udp
    depends_on:
      svelte-kit:
        condition: service_healthy
      pocketbase:
        condition: service_healthy
    volumes:
      - ./docker/caddy/Caddyfile:/etc/caddy/Caddyfile
      - ./data/caddy/data:/data
      - ./data/caddy/config:/config

  svelte-kit:
    build:
      context: .
      dockerfile: docker/bun/Dockerfile
    restart: unless-stopped
    container_name: rl-svelte-kit
    working_dir: /home/bun/svelte-kit
    entrypoint: ["./scripts/bun.sh"]
    stdin_open: true
    tty: true
    depends_on:
      pocketbase:
        condition: service_healthy
    environment:
      - ORIGIN=http://local.ranky-list.com
    volumes:
      - svelte-kit-volume:/home/bun/svelte-kit
    healthcheck:
      test: wget --no-verbose --tries=1 --spider http://localhost:5173/api/healthz || exit 1
      timeout: 20s
      retries: 10
      start_period: 60s
      interval: 60s
      start_interval: 1s

  histoire:
    build:
      context: .
      dockerfile: docker/bun/Dockerfile
    restart: unless-stopped
    container_name: rl-histoire
    command: bun run story:dev --port 6006
    working_dir: /home/bun/histoire
    stdin_open: true
    tty: true
    volumes:
      - svelte-kit-volume:/home/bun/histoire
    depends_on:
      svelte-kit:
        condition: service_healthy

  mailcatcher:
    image: sj26/mailcatcher:latest
    restart: unless-stopped
    container_name: rl-mailcatcher

  pocketbase:
    build:
      context: .
      dockerfile: ./docker/pocketbase/Dockerfile
    restart: unless-stopped
    container_name: rl-pocketbase
    command: wgo run -xdir pb_data main.go serve --http 0.0.0.0:8090
    stdin_open: true
    tty: true
    environment:
      DB_USER: "${DB_USER:?err}"
      DB_PASS: "${DB_PASS:?err}"
    volumes:
      - ./pocketbase:/usr/src/app
    healthcheck:
      test: wget --no-verbose --tries=1 --spider http://localhost:8090/api/health || exit 1
      timeout: 20s
      retries: 10
      start_period: 60s
      interval: 60s
      start_interval: 1s

volumes:
  svelte-kit-volume:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${PWD}/svelte-kit
