version: '3.3'

services:
  svelte-kit:
    build:
      context: .
      dockerfile: docker/svelte-kit/Dockerfile
    volumes:
      - "./svelte-kit:/usr/src/svelte-kit"
      - "/usr/src/svelte-kit/node_modules"
    stdin_open: true
    tty: true
    ports:
      - 5173:5173
    restart: unless-stopped
    container_name: rl-svelte-kit

  nest:
    build:
      context: .
      dockerfile: docker/nest/Dockerfile
    volumes:
      - "./nest:/usr/src/nest"
      - "/usr/src/nest/node_modules"
    stdin_open: true
    tty: true
    ports:
      - 3000:3000
    restart: unless-stopped
    container_name: rl-nest

  mongo:
    image: mongo:latest
    restart: unless-stopped
    container_name: rl-mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: "${MONGO_INITDB_ROOT_USERNAME:?err}"
      MONGO_INITDB_ROOT_PASSWORD: "${MONGO_INITDB_ROOT_PASSWORD:?err}"

  mongo-express:
    image: mongo-express
    restart: unless-stopped
    ports:
      - 8081:8081
    container_name: rl-mongo-express
    depends_on:
      - mongo
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: "${MONGO_INITDB_ROOT_USERNAME:?err}"
      ME_CONFIG_MONGODB_ADMINPASSWORD: "${MONGO_INITDB_ROOT_PASSWORD:?err}"
      ME_CONFIG_MONGODB_URL: "mongodb://${MONGO_INITDB_ROOT_USERNAME:?err}:${MONGO_INITDB_ROOT_PASSWORD:?err}@mongo:27017/"

  mailcatcher:
    image: sj26/mailcatcher:latest
    ports:
      - 1080:1080
    container_name: rl-mailcatcher
