version: '3.9'

services:
  svelte-kit:
    build:
      context: .
      dockerfile: docker/svelte-kit/Dockerfile
    ports:
      - 5173:5173
    depends_on:
      pocketbase:
        condition: service_healthy
    volumes:
      - ./svelte-kit:/home/node/svelte-kit
    stdin_open: true
    tty: true
    restart: unless-stopped
    container_name: rl-svelte-kit
    healthcheck:
      test: wget http://localhost:5173 -q --spider || exit 1
      timeout: 30s
      interval: 2s
      retries: 30

  playwright:
    image: mcr.microsoft.com/playwright:v1.31.2-focal
    restart: "no"
    working_dir: /testing
    command: [ "yarn", "test" ]
    volumes:
      - ./svelte-kit:/testing
    depends_on:
      svelte-kit:
        condition: service_healthy
    container_name: rl-playwright

  storybook:
    build:
      context: .
      dockerfile: docker/storybook/Dockerfile
    ports:
      - 6006:6006
    depends_on:
      svelte-kit:
        condition: service_healthy
    volumes:
      - ./svelte-kit:/home/node/storybook
    stdin_open: true
    tty: true
    restart: unless-stopped
    container_name: rl-storybook

  mailcatcher:
    image: sj26/mailcatcher:latest
    restart: unless-stopped
    ports:
      - 1080:1080
    container_name: rl-mailcatcher

  pocketbase:
    image: ghcr.io/muchobien/pocketbase:latest
    container_name: rl-pocketbase
    restart: unless-stopped
    ports:
      - 8090:8090
    volumes:
      - ./data/pocketbase/data:/pb_data
      - ./data/pocketbase/public:/pb_public
    healthcheck:
      test: wget --no-verbose --tries=1 --spider http://localhost:8090/api/health || exit 1
      interval: 5s
      timeout: 5s
      retries: 5
