version: '3.3'

services:
  playwright:
    build:
      context: .
      dockerfile: docker/CI/playwright/Dockerfile
    restart: "no"
    depends_on:
      mariadb:
        condition: service_healthy
    container_name: rl-playwright

  mariadb:
    image: mariadb:10.10.2
    restart: unless-stopped
    container_name: rl-mariadb
    environment:
      MARIADB_ROOT_PASSWORD_HASH: "${MARIADB_ROOT_PASSWORD_HASH:?err}"
      MARIADB_USER: "${MARIADB_USER:?err}"
      MARIADB_PASSWORD_HASH: "${MARIADB_PASSWORD_HASH:?err}"
      MARIADB_DATABASE: "${MARIA_DATABASE:-ranky_list}"
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      timeout: 30s
      interval: 2s
      retries: 30
