version: '3.3'

services:
  svelte-kit:
    build:
      context: .
      dockerfile: docker/svelte-kit/Dockerfile
    volumes:
      - "./svelte-kit:/usr/src/svelte-kit"
      - "/usr/src/svelte-kit/node_modules"
    stdin_open: true
    tty: true
    ports:
      - 5173:5173
    restart: unless-stopped
    container_name: rl-svelte-kit

  nest:
    build:
      context: .
      dockerfile: docker/nest/Dockerfile
    volumes:
      - "./nest:/usr/src/nest"
      - "/usr/src/nest/node_modules"
    stdin_open: true
    tty: true
    ports:
      - 3000:3000
    restart: unless-stopped
    container_name: rl-nest

  mariadb:
    image: mariadb:10.10.2
    restart: unless-stopped
    container_name: rl-mariadb
    environment:
      MARIADB_RANDOM_ROOT_PASSWORD: yes
      MARIADB_USER: "${MARIADB_USER:?err}"
      MARIADB_PASSWORD_HASH: "${MARIADB_PASSWORD_HASH:?err}"
      MARIADB_DATABASE: "${MARIA_DATABASE:-ranky-list}"

  phpmyadmin:
    image: phpmyadmin
    restart: unless-stopped
    container_name: rl-phpmyadmin
    ports:
      - 8080:80
    environment:
      - PMA_ARBITRARY=1

  mailcatcher:
    image: sj26/mailcatcher:latest
    ports:
      - 1080:1080
    container_name: rl-mailcatcher
