version: '3.9'

services:
  svelte-kit:
    build:
      context: .
      dockerfile: docker/svelte-kit/Dockerfile
    ports:
      - 5173:5173
    depends_on:
      mariadb:
        condition: service_healthy
    volumes:
      - "./svelte-kit:/home/node/svelte-kit"
    stdin_open: true
    tty: true
    restart: unless-stopped
    container_name: rl-svelte-kit
    healthcheck:
      test:
        [
          "CMD",
          "wget",
          "http://localhost:5173",
          "-q",
          "--spider"
        ]
      timeout: 30s
      interval: 2s
      retries: 30

  mariadb:
    image: mariadb:10.10.2
    restart: unless-stopped
    container_name: rl-mariadb
    volumes:
      - ./data/mysql:/var/lib/mysql
    environment:
      MARIADB_ROOT_PASSWORD_HASH: "${MARIADB_ROOT_PASSWORD_HASH:?err}"
      MARIADB_USER: "${MARIADB_USER:?err}"
      MARIADB_PASSWORD_HASH: "${MARIADB_PASSWORD_HASH:?err}"
      MARIADB_DATABASE: "${MARIA_DATABASE:-ranky_list}"
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      timeout: 30s
      interval: 2s
      retries: 30

  phpmyadmin:
    image: phpmyadmin
    restart: unless-stopped
    container_name: rl-phpmyadmin
    ports:
      - 8080:80
    depends_on:
      mariadb:
        condition: service_healthy
    environment:
      - PMA_ARBITRARY=1

  playwright:
    image: mcr.microsoft.com/playwright:v1.31.2-focal
    restart: "no"
    working_dir: /testing
    command: [ "yarn", "test" ]
    volumes:
      - ./svelte-kit:/testing
    depends_on:
      mariadb:
        condition: service_healthy
      svelte-kit:
        condition: service_healthy
    container_name: rl-playwright

  storybook:
    build:
      context: .
      dockerfile: docker/storybook/Dockerfile
    ports:
      - 6006:6006
    depends_on:
      svelte-kit:
        condition: service_healthy
    volumes:
      - "./svelte-kit:/home/node/storybook"
    stdin_open: true
    tty: true
    restart: unless-stopped
    container_name: rl-storybook

  mailcatcher:
    image: sj26/mailcatcher:latest
    restart: unless-stopped
    ports:
      - 1080:1080
    container_name: rl-mailcatcher
