version: '3.9'

services:
  svelte-kit:
    build:
      context: .
      dockerfile: docker/svelte-kit/Dockerfile
    ports:
      - 5173:5173
    depends_on:
      pocketbase:
        condition: service_healthy
    volumes:
      - svelte-kit-volume:/home/node/svelte-kit
    stdin_open: true
    tty: true
    restart: unless-stopped
    container_name: rl-svelte-kit
    healthcheck:
      test: wget --no-verbose --tries=1 --spider http://localhost:5173/api/healthz || exit 1
      timeout: 30s
      interval: 2s
      retries: 30

  vitest:
    build:
      context: .
      dockerfile: docker/vitest/Dockerfile
    ports:
      - 5174:5174
    depends_on:
      svelte-kit:
        condition: service_healthy
    volumes:
      - svelte-kit-volume:/home/node/testing
    stdin_open: true
    tty: true
    restart: unless-stopped
    container_name: rl-vitest

  playwright:
    image: mcr.microsoft.com/playwright:v1.33.0-focal
    restart: "no"
    working_dir: /testing
    command: [ "yarn", "test" ]
    volumes:
      - svelte-kit-volume:/testing
    depends_on:
      svelte-kit:
        condition: service_healthy
    container_name: rl-playwright

  storybook:
    build:
      context: .
      dockerfile: docker/storybook/Dockerfile
    ports:
      - 6006:6006
    depends_on:
      svelte-kit:
        condition: service_healthy
    volumes:
      - svelte-kit-volume:/home/node/storybook
    stdin_open: true
    tty: true
    restart: unless-stopped
    container_name: rl-storybook

  mailcatcher:
    image: sj26/mailcatcher:latest
    restart: unless-stopped
    ports:
      - 1080:1080
    container_name: rl-mailcatcher

  pocketbase:
    build:
      context: .
      dockerfile: ./docker/pocketbase/Dockerfile
    ports:
      - 8090:8090
    command: wgo run -xdir pb_data main.go serve --http 0.0.0.0:8090
    volumes:
      - ./pocketbase:/usr/src/app
    environment:
      DB_USER: "${DB_USER:?err}"
      DB_PASS: "${DB_PASS:?err}"
    stdin_open: true
    tty: true
    restart: unless-stopped
    container_name: rl-pocketbase
    healthcheck:
      test: wget --no-verbose --tries=1 --spider http://localhost:8090/api/health || exit 1
      interval: 20s
      timeout: 5s
      retries: 5

volumes:
  svelte-kit-volume:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${PWD}/svelte-kit
