name: Question
description: Ask something
title: "[QUESTION] <title>"
labels: [question]
body:
  - type: markdown
    attributes:
      value: |
        Questions should generally be asked on the Discord server instead, but it can also be relevant to ask here.
  - type: textarea
    id: question
    attributes:
      label: Question
      description: Ask your question.
    validations:
      required: true
  - type: textarea
    id: info
    attributes:
      label: Additional information
      description: Add anything you feel like is necessary for this question.
  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our [Code of Conduct](https://github.com/RankyList/ranky-list/blob/master/CODE_OF_CONDUCT.md).
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true
