# TODO add a Docker run command ?

# E2E
e2e:
	bunx playwright test

e2e-ui:
	bunx playwright test --ui

e2e-report:
	bunx playwright show-report

# Linting
lint:
	bun run lint

format:
	bun run format
