name: Code linting

on: [push, pull_request]

jobs:
  eslint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Start the containers
        run: make start

      - name: Run ESLint
        run: make lint
