name: Code linting

on: [pull_request]

jobs:
  eslint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Run ESLint (includes Prettier)
        run: make ci-eslint
