name: Code linting

on: [pull_request]

jobs:
  eslint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install dependencies
        working-directory: ./svelte-kit
        run: yarn install

      - name: Run ESLint
        working-directory: ./svelte-kit
        run: yarn lint
