name: Code linting

on: [pull_request]

jobs:
  eslint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Start the containers
        run: make start-ci

      - name: Run ESLint
        run: make lint
