name: Linting SvelteKit

on:
  pull_request:
    branches:
      - '**'
    types:
      - opened
      - synchronize
      - reopened
      - ready_for_review
    paths:
      - "svelte-kit/**"
      - ".github/workflows/lint-sveltekit.yml"

  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  lint-sveltekit:
    name: Lint SvelteKit

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: 1.0.30

      - name: Install dependencies
        working-directory: ./svelte-kit
        run: bun install

      - name: Check SvelteKit config & generate types
        working-directory: ./svelte-kit
        run: bun run check

      - name: Run linter
        working-directory: ./svelte-kit
        run: bun run lint

      - name: Check the build phase
        working-directory: ./svelte-kit
        run: bun run build
