name: Code linting

on: [pull_request]

jobs:
  eslint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install dependencies
        working-directory: ./svelte-kit
        run: yarn install

      - name: Generate Prisma types
        working-directory: ./svelte-kit
        run: yarn prisma:generate

      - name: Sync & Check
        working-directory: ./svelte-kit
        run: yarn check

      - name: Log
        working-directory: ./svelte-kit
        run: ls ./.svelte-kit/types

      - name: Run ESLint (includes Prettier)
        working-directory: ./svelte-kit
        run: yarn lint
