name: Code testing

on: [pull_request]

jobs:
  playwright:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Start the db
        run: make build-pocketbase

      - name: Run Playwright
        run: make ci-playwright

  vitest:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Start the db
        run: make build-pocketbase

      - name: Run Vitest
        run: make ci-vitest
