name: Code testing

on: [pull_request]

jobs:
  playwright:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Start the containers
        run: make start-ci

      - name: Run Playwright
        run: make playwright

  vitest:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Start the containers
        run: make start-ci

      - name: Run Vitest
        run: make vitest
